package io.github.sinri.keel.base.json;

import io.vertx.core.json.JsonObject;
import io.vertx.core.shareddata.Shareable;
import org.jetbrains.annotations.NotNull;

import java.lang.reflect.InvocationTargetException;


/**
 * 本接口定义了一类基于 JSON 对象的只读封装。
 * <p>
 * 本接口的实现类应提供一个构造函数，接受 {@link JsonObject} 类型的唯一参数。
 *
 * @since 5.0.0
 */
public interface UnmodifiableJsonifiableEntity
        extends JsonObjectReadable, JsonSerializable, Shareable {

    /**
     * Wraps a {@link JsonObject} into an instance of the specified class, which must be a subtype of
     * {@link UnmodifiableJsonifiableEntity}. The specified class must have a constructor that accepts a
     * {@link JsonObject} as its parameter.
     *
     * @param <U>        the type of the class to wrap the {@link JsonObject} into, extending
     *                   {@link UnmodifiableJsonifiableEntity}
     * @param jsonObject a non-null {@link JsonObject} that will be wrapped
     * @param clazz      the class type of the resulting object, must have a constructor accepting a {@link JsonObject}
     * @return an instance of the specified class wrapping the provided {@link JsonObject}
     * @throws NoSuchMethodException     if the specified class does not have the required constructor
     * @throws InvocationTargetException if the constructor throws an exception
     * @throws InstantiationException    if the specified class cannot be instantiated
     * @throws IllegalAccessException    if the constructor is not accessible
     * @since 4.1.5
     */
    @NotNull
    static <U extends UnmodifiableJsonifiableEntity> U wrap(@NotNull JsonObject jsonObject, Class<U> clazz) throws NoSuchMethodException, InvocationTargetException, InstantiationException, IllegalAccessException {
        return clazz.getConstructor(JsonObject.class).newInstance(jsonObject);
    }

    @NotNull
    static UnmodifiableJsonifiableEntity wrap(@NotNull JsonObject jsonObject) {
        return new UnmodifiableJsonifiableEntityImpl(jsonObject);
    }

    /**
     * A COPIED {@link JsonObject} instance generated as required; should not be a cached value.
     * <p>
     * By default, it is designed to be regenerated from the JSON expression by
     * {@link JsonSerializable#toJsonExpression()}.
     *
     * @return A JSON Object composed by the string generated by
     *         `io.github.sinri.keel.core.json.UnmodifiableJsonifiableEntity#toJsonExpression()`.
     * @since 3.2.17
     */
    @NotNull
    default JsonObject cloneAsJsonObject() {
        return new JsonObject(toJsonExpression());
    }

}
